### ISSUE TITLE
build fails on Windows with "java.nio.file.InvalidPathException: Illegal char <"> at index 29: D:\Projects\android-cli-tools""

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/bubblewrap#149]
Full error
```
PS D:\Projects\llama-pack-project> node ..\llama-pack\packages\cli\bin\bubblewrap.js build
Installing Android Build Tools. Please, read and accept the license agreement
Installing Build Tools
Warning: Could not create settings
java.nio.file.InvalidPathException: Illegal char <"> at index 29: D:\Projects\android-cli-tools"
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.<init>(SdkManagerCliSettings.java:407)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:152)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:134)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:57)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
```

**Comment by andreban** [comment]
Closed via #148
