### ISSUE TITLE
Upgrading to Version 1.4.1 throws Error : Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by naveedahmed1** [GoogleChromeLabs/bubblewrap#257]
**Describe the bug**
I recently upgraded the `@bubblewrap/cli` to the latest version using `npm i -g @bubblewrap/cli` command.

**Update bubblewrap cli**
```
npm i -g @bubblewrap/cli
C:\Users\Naveed Ahmed\AppData\Roaming\npm\bubblewrap -> C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\bin\bubblewrap.js
+ @bubblewrap/cli@1.4.1
updated 1 package in 18.987s
```

**Update Project**
After updating `bubblewrap/cli` when I tried to update my project using `bubblewrap update` command, its throwing below error:
```
bubblewrap update

Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\sharp\lib\constructor.js
- C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\sharp\lib\index.js
- C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\@bubblewrap\core\dist\lib\TwaGenerator.js
- C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\@bubblewrap\core\dist\index.js
- C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\dist\lib\cmds\update.js
- C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\dist\lib\Cli.js
- C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\dist\index.js
- C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\bin\bubblewrap.js

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

```

**To Reproduce**
1. Update existing verson of bubblewrap cli using command `npm i -g @bubblewrap/cli`
2. Run `bubblewrap update` command to update project
3. It will throw above error

**Expected behavior**
The upgrade process should be very smooth and work without throwing any error.
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser :Chrome
 - Version 84.0.4147.89

**Comment by andreban** [comment]
Unfortunately, this issue comes from Sharp. Did the following work?
```
- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

**Comment by naveedahmed1** [comment]
Unfortunately no, removing `node_mobules/sharp` throws below error:

```
npm i -g @bubblewrap/cli
C:\Users\Naveed Ahmed\AppData\Roaming\npm\bubblewrap -> C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\bin\bubblewrap.js

> sharp@0.23.4 install C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\Naveed Ahmed\AppData\Roaming\npm-cache\_libvips\libvips-8.8.1-win32-x64.tar.gz
info sharp Creating C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\sharp\vendor\lib to C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=14.5.0 runtime=node arch=x64 libc= platform=win32)

C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.6.30309.148) found at:
gyp ERR! find VS "d:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\node_modules\sharp
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.23.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naveed Ahmed\AppData\Roaming\npm-cache\_logs\2020-07-22T12_07_09_183Z-debug.log
```

I have VS 2019 already installed.

**Comment by andreban** [comment]
That's annoying. Seems like `sharp` doesn't have pre-compiled binaries for your architecture (and I wouldn't expect people having to compile the dependencies themselves).

Right now we're considering reverting the move to sharp - It gives us SVG support, but also created #240, #258 and this issue.

**Comment by andreban** [comment]
Created #259 to discuss reverting from sharp.

**Comment by naveedahmed1** [comment]
Ok, thank you @andreban :)

**Comment by andreban** [comment]
`1.5.0` removes sharp and restores jimp. Can you confirm it works as expected?

**Comment by naveedahmed1** [comment]
Thanks @andreban . I was able to install with `--force` flag, without which it was throwing below error:

```
npm ERR! code EEXIST
npm ERR! path C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\bin\bubblewrap.js
npm ERR! dest C:\Users\Naveed Ahmed\AppData\Roaming\npm\bubblewrap
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\Naveed Ahmed\AppData\Roaming\npm\node_modules\@bubblewrap\cli\bin\bubblewrap.js' -> 'C:\Users\Naveed Ahmed\AppData\Roaming\npm\bubblewrap'
npm ERR! File exists: C:\Users\Naveed Ahmed\AppData\Roaming\npm\bubblewrap
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naveed Ahmed\AppData\Roaming\npm-cache\_logs\2020-07-27T01_23_05_409Z-debug.log
```
