### ISSUE TITLE
App shortcuts return "App not installed"

### ISSUE THREAD

**Issue by justrealmilk** [GoogleChromeLabs/bubblewrap#335]
**Describe the bug**
Upon attempting to use an app shortcut, the user is greeted with "App not installed."

**To Reproduce**
Do a bubblewrap

**Expected behavior**
Shortcuts to work

**Smartphone**
 - Device: Pixel 4
 - OS: 11
 - Browser: Chrome

And a Samsung A8 to ensure I'm not going insane.

**Additional context**
I've installed and setup Android Studio for the first time and manager to grab this error from the emulator upon attempting to use the shortcuts:

```
2020-09-15 11:36:56.194 2405-2405/? E/BaseDraggingActivity: Unable to launch. tag=WorkspaceItemInfo(id=-1 type=DEEPSHORTCUT container=-1 screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=1 user=UserHandle{0} title=Triumphs) intent=Intent { act=android.intent.action.MAIN cat=[com.android.launcher3.DEEP_SHORTCUT] flg=0x10200000 pkg=package.name.twa cmp=package.name.twa/.LauncherActivity bnds=[60,634][665,788] (has extras) }
    android.content.ActivityNotFoundException: Shortcut could not be started
        at android.content.pm.LauncherApps.startShortcut(LauncherApps.java:1144)
        at android.content.pm.LauncherApps.startShortcut(LauncherApps.java:1109)
        at com.android.launcher3.shortcuts.DeepShortcutManager.startShortcut(SourceFile:1)
        at com.android.launcher3.BaseDraggingActivity.startShortcutIntentSafely(SourceFile:10)
        at com.android.launcher3.BaseDraggingActivity.startActivitySafely(SourceFile:11)
        at com.android.launcher3.Launcher.startActivitySafely(SourceFile:6)
        at com.android.launcher3.touch.ItemClickHandler.startAppShortcutOrInfoActivity(SourceFile:15)
        at com.android.launcher3.touch.ItemClickHandler.onClickAppShortcut(SourceFile:13)
        at com.android.launcher3.touch.ItemClickHandler.a(SourceFile:12)
        at c.a.a.p.c.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7125)
        at com.android.launcher3.shortcuts.DeepShortcutTextView.performClick(SourceFile:9)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

The shortcuts are generated obviously but here's an example:
```xml
    <shortcut android:shortcutId='shortcut3' android:enabled='true' android:icon='@drawable/shortcut_3' android:shortcutShortLabel='@string/shortcut_short_name_3' android:shortcutLongLabel='@string/shortcut_name_3'>
        <intent android:action='android.intent.action.MAIN' android:targetPackage='package.name.twa' android:targetClass='com.google.androidbrowserhelper.trusted.LauncherActivity' android:data='https://twa/url?utm_source=shortcut' />
        <categories android:name='android.intent.category.LAUNCHER' />
    </shortcut>
```

**Comment by andreban** [comment]
@justrealmilk Could you share the APK for the app? I do see something that doesn't seem correct: The Intent tries to open the package `braytech.org.twa`, but the shortcut snipped has package `package.name.twa`.

**Comment by justrealmilk** [comment]
> @justrealmilk Could you share the APK for the app? I do see something that doesn't seem correct: The Intent tries to open the package `braytech.org.twa`, but the shortcut snippet has package `package.name.twa`. `android:data` also points to an invalid URL.

That was a failure to censor on my part 😂

**Comment by dejancencelj** [comment]
I also reported the bug here

https://github.com/pwa-builder/PWABuilder/issues/1126

**Comment by dejancencelj** [comment]
[RTVSLO.si_10_0_30_0.apk.zip](https://github.com/GoogleChromeLabs/bubblewrap/files/5274227/RTVSLO.si_10_0_30_0.apk.zip)

**Comment by dejancencelj** [comment]
I've attached the APK so it's easier to test

**Comment by andreban** [comment]
@dejancencelj I can repro using the APK you provided, thank you. @rayankans, files in the APK seem correct - any idea what may be going wrong?

**Comment by andreban** [comment]
Ok, found the problem - This was broken by #278, which changed the main Activity to `com.phonegap.rtv.LauncherActivity`, but the shortcut is pointing to `com.google.androidbrowserhelper.trusted.LauncherActivity`. Will work on a fix.
