### ISSUE TITLE
Error: Cannot find module '../build/Release/canvas.node' after installing bubblerwap globally

### ISSUE THREAD

**Issue by raymeskhoury** [GoogleChromeLabs/bubblewrap#406]
Installation works fine but trying to run after installation fails. It works with a non-global install.

```
raymes@raymes:/usr/local/lib/node_modules$ sudo npm i -g @bubblewrap/cli
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/bubblewrap -> /usr/local/lib/node_modules/@bubblewrap/cli/bin/bubblewrap.js

> canvas@2.6.1 install /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvas
> node-pre-gyp install --fallback-to-build


raymes@raymes:/usr/local/lib/node_modules$ bubblewrap --help
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvas/lib/bindings.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvas/lib/canvas.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvas/index.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/utils.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/living/generated/MouseEvent.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/living/interfaces.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/browser/Window.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/api.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/svg2img/index.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/@bubblewrap/core/dist/lib/wrappers/svg2img.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/@bubblewrap/core/dist/lib/ImageHelper.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/@bubblewrap/core/dist/lib/TwaGenerator.js
- /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/@bubblewrap/core/dist/index.js
- /usr/local/lib/node_modules/@bubblewrap/cli/dist/lib/cmds/update.js
- /usr/local/lib/node_modules/@bubblewrap/cli/dist/lib/Cli.js
- /usr/local/lib/node_modules/@bubblewrap/cli/dist/index.js
- /usr/local/lib/node_modules/@bubblewrap/cli/bin/bubblewrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvas/lib/bindings.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvas/lib/canvas.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvas/index.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/utils.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/living/generated/MouseEvent.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/living/interfaces.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/jsdom/browser/Window.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/jsdom/lib/api.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/svg2img/index.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/@bubblewrap/core/dist/lib/wrappers/svg2img.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/@bubblewrap/core/dist/lib/ImageHelper.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/@bubblewrap/core/dist/lib/TwaGenerator.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/@bubblewrap/core/dist/index.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/dist/lib/cmds/update.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/dist/lib/Cli.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/dist/index.js',
    '/usr/local/lib/node_modules/@bubblewrap/cli/bin/bubblewrap.js'
  ]
}
```

**Comment by andreban** [comment]
Thanks for filing this, @raymeskhoury 

This seems similar to #379 where installing Bubblewrap with `sudo` results in lacking permission to install the native libraries required by `svg2img` to `/usr/local/lib/node_modules/`.

Can you confirm:

- Operating System
- Node.Js version

**Comment by andreban** [comment]
FYI: Added a [warning](https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#installing-bubblewrap) around installing Bubblewrap with `sudo` to the docs.

**Comment by raymeskhoury** [comment]
Thanks! 
```
~$ nodejs --version
v12.18.4
~$ cat /etc/debian_version
rodete
```

Is it possible to install bubblewrap globally then (without messing about with filesystem permissions)? I tried running it without sudo and I get filesystem permission errors:

```
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
```

**Comment by andreban** [comment]
This is related to [this StackOverflow question](https://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo). The thread advices using [nvm](https://github.com/nvm-sh/nvm) to manage Node.js. This [page](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) recommends the same but describes how to fix the permissions manually.
