### ISSUE TITLE
Cannot find module '../dist'

### ISSUE THREAD

**Issue by Porshe** [GoogleChromeLabs/bubblewrap#479]
After install bubblewrap
`npm i -g @bubblewrap/cli`

When run command `bubblewrap doctor`

I get an error

```
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '../dist'
Require stack:
- /usr/local/lib/node_modules/@bubblewrap/cli/bin/bubblewrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bubblewrap/cli/bin/bubblewrap.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/@bubblewrap/cli/bin/bubblewrap.js' ]
}

Node version: v12.19.0
npm version: 6.14.11

**Comment by andreban** [comment]
Can you run `bubblewrap --version` and paste the output? Do other commands work?

**Comment by Porshe** [comment]
> Can you run `bubblewrap --version` and paste the output? Do other commands work?

root@vultr:/tmp/twa_build_6040d37e1f76a# bubblewrap --version
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '../dist'
Require stack:
- /usr/local/lib/node_modules/@bubblewrap/cli/bin/bubblewrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bubblewrap/cli/bin/bubblewrap.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/@bubblewrap/cli/bin/bubblewrap.js' ]
}

**Comment by andreban** [comment]
Thanks - it seems I broke it when publishing earlier today - `npm install @bubblewrap/cli@1.10.0` should enabling installing the previous working version. Nevertheless, I just published `1.11.1`, which should fix the issue `npm update -g @bubblewrap/cli` to get the version.

**Comment by andreban** [comment]
Seems to work after `npm update -g @bubblewrap/cli`:

```
~/Projects/twa-project via ☕ v1.8.0 
❯ bubblewrap --version
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
                                                           `--'    
version 1.11.1

~/Projects/twa-project via ☕ v1.8.0 
❯ bubblewrap doctor
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
                                                           `--'    
doctor Your jdkpath and androidSdkPath are valid.

~/Projects/twa-project via ☕ v1.8.0 

```

**Comment by Porshe** [comment]
> Thanks - it seems I broke it when publishing earlier today - `npm install @bubblewrap/cli@1.10.0` should enabling installing the previous working version. Nevertheless, I just published `1.11.1`, which should fix the issue `npm update -g @bubblewrap/cli` to get the version.

thank you.

File assetlinks.json no more generates?

**Comment by andreban** [comment]
@Porshe we removed that, since most of the time it is generating the wrong fingerprint (due to Play Store Signing). You can follow [these steps](https://developer.chrome.com/docs/android/trusted-web-activity/quick-start/#play-store-signing) to check the Fingerprint after uploading the app to the Play Store. Then use `bubblewrap fingerprint add [fingerprint-from-play]` to add to the fingerprint list. This will generate the correct `assetlinks.json`.

**Comment by andreban** [comment]
Closing this, as #481 confirms the fix.
