### ISSUE TITLE
bubblewrap CLI throws error for any command

### ISSUE THREAD

**Issue by jahooma** [GoogleChromeLabs/bubblewrap#593]
**Describe the bug**
Running bubblewrap init to generate my TWA gives an error.

**To Reproduce**
On a Mac with Node v15.12.0
1. npm i - g @bubblewrap/cli
2. bubblewrap init --manifest https://throne.live/manifest.json
3. Got the error:

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvg/lib/index.js
require() of ES modules is not supported.
require() of /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvg/lib/index.js from /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/svg2img/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvg/lib/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvg/package.json.

    at new NodeError (node:internal/errors:329:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1109:13)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/svg2img/index.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32) {
  code: 'ERR_REQUIRE_ESM'

**Comment by m-ochyra** [comment]
The same error on Mac with Node 12.22.1.

```
internal/modules/cjs/loader.js:1015
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvg/lib/index.js
require() of ES modules is not supported.
require() of /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvg/lib/index.js from /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/svg2img/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvg/lib/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/local/lib/node_modules/@bubblewrap/cli/node_modules/canvg/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/svg2img/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by andreban** [comment]
I can reproduce. This seems related to https://github.com/fuzhenn/node-svg2img/issues/59

**Comment by andreban** [comment]
This shouldn't happen anymore on [`1.13.6`](https://www.npmjs.com/package/@bubblewrap/cli/v/1.13.6), which pins the `canvg` version to `3.0.7`. Please, re-open if you can still reproduce.
