### ISSUE TITLE
Cannot install version 1.13.6

### ISSUE THREAD

**Issue by m-ochyra** [GoogleChromeLabs/bubblewrap#595]
**Describe the bug**
I cannot install version 1.13.6.

**To Reproduce**
`npm install -g @bubblewrap/cli` installs varsion 1.13.5.
`npm install -g @bubblewrap/cli@1.13.6` returns error
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @bubblewrap/cli@1.13.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Log:
```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   '@bubblewrap/cli@1.13.6'
0 verbose cli ]
1 info using npm@7.23.0
2 info using node@v14.17.6
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/m.ochyra/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:validate Completed in 3ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 15ms
18 timing npm:load:configload Completed in 15ms
19 timing npm:load:setTitle Completed in 19ms
20 timing npm:load:setupLog Completed in 0ms
21 timing config:load:flatten Completed in 6ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 44ms
26 timing arborist:ctor Completed in 1ms
27 timing idealTree:init Completed in 6ms
28 timing idealTree:userRequests Completed in 4ms
29 silly idealTree buildDeps
30 silly fetch manifest @bubblewrap/cli@1.13.6
31 http fetch GET 200 https://repo.huaweicloud.com/repository/npm/@bubblewrap%2fcli 2601ms (cache miss)
32 silly placeDep ROOT @bubblewrap/cli@ OK for:  want: 1.13.6
33 timing idealTree:#root Completed in 2611ms
34 timing idealTree:node_modules/@bubblewrap/cli Completed in 0ms
35 timing idealTree:buildDeps Completed in 2613ms
36 timing idealTree:fixDepFlags Completed in 1ms
37 timing idealTree Completed in 2625ms
38 timing command:install Completed in 2673ms
39 verbose type version
40 verbose stack @bubblewrap/cli: No matching version found for @bubblewrap/cli@1.13.6.
40 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
40 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
40 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1032:19)
40 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:906:11)
40 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:210:7)
40 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:147:5)
40 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:169:5)
41 verbose cwd /Users/m.ochyra
42 verbose Darwin 20.5.0
43 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "@bubblewrap/cli@1.13.6"
44 verbose node v14.17.6
45 verbose npm  v7.23.0
46 error code ETARGET
47 error notarget No matching version found for @bubblewrap/cli@1.13.6.
48 error notarget In most cases you or one of your dependencies are requesting
48 error notarget a package version that doesn't exist.
49 verbose exit 1
```

**Expected behavior**
Both methods should install version 1.13.6
![image](https://user-images.githubusercontent.com/5583015/133735585-4ed3ab11-6fd5-4a01-acd0-05e09564dbfd.png)

**Comment by andreban** [comment]
I can't repro this on MacOS, and it installs without issues. Which OS and Node version are you using?

**Comment by m-ochyra** [comment]
I'm using  macOS 11.4 Big Sur and
```
npm@7.23.0
node@v14.17.6
```

**Comment by andreban** [comment]
Tried Node 14.17.7, but can't repro.

![Screenshot 2021-09-17 at 09 33 42](https://user-images.githubusercontent.com/1733592/133751711-9c49d322-f9cf-49dc-bf62-607d58c087c7.png)

It seems to be cache missing when installing from NPM, but v1.13.6 is definitely there: https://www.npmjs.com/package/@bubblewrap/cli/v/1.13.6

**Comment by m-ochyra** [comment]
I don't know what is going on, but yarn also can't install v1.13.6
![image](https://user-images.githubusercontent.com/5583015/133962039-efe6c2f2-b873-430f-8c5d-b44bbd758aae.png)

**Comment by andreban** [comment]
Can you access https://unpkg.com/@bubblewrap/cli@1.13.6/package.json? I'm wondering if there's a proxy / cache somewhere.

**Comment by m-ochyra** [comment]
Yes, I have access. I can see v1.13.6 everywhere, but my npm can't.
I tried reinstall node and npm but still no success.

**Comment by andreban** [comment]
Any chance the NPM requests are being proxied? The following line on the log shared on the first message made me wonder:

```
31 http fetch GET 200 https://repo.huaweicloud.com/repository/npm/@bubblewrap%2fcli 2601ms (cache miss)
```

**Comment by m-ochyra** [comment]
In browser at this address I can see that the newest version is 1.13.5
![image](https://user-images.githubusercontent.com/5583015/134152095-a59ca332-0317-4cfe-9be6-31fde88ab050.png)

I have direct connection with my network provider. No firewalls, no proxies.

**Comment by m-ochyra** [comment]
I'm closing this issue due I installed newest version on my other mac and couple of my colleagues can install version 1.13.6 now.
