### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by liemteksun** [GoogleChromeLabs/bubblewrap#602]
**Describe the bug**
I run into an exception when running
bubblewrap init --manifest https://my-twa.com/manifest.json

**To Reproduce**
1. run 
**bubblewrap init --manifest https://my-twa.com/manifest.json**
this is the error
```
/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bubblewrap/cli/node_modules/googleapis-common/build/src/apirequest.js:20:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - NodeJs: v14.18.0
 - npm: 6.14.15

thanks

**Comment by andreban** [comment]
I can't reproduce this on my Linux box, using the same Node and npm versions. Any ideas on what else could be different in your system so I can try reproducing?

**Comment by liemteksun** [comment]
It seems that I download bubblewrap with nodejs v 8
I reinstall and it works now

thanks
