### ISSUE TITLE
Packaging for Arch Linux Question

### ISSUE THREAD

**Issue by NicoHood** [GoogleChromeLabs/bubblewrap#659]
Hey guys,
I'd like to bring this software to the Arch repos. However it does not build for some reason in the chroot environment. On my user system it works fine, so I guess it is a missing dependency?

The error message:
```
==> Starting package()...
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 613 packages, and audited 614 packages in 58s

71 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm ERR! code 127
npm ERR! path /build/bubblewrap-pwa/pkg/bubblewrap-pwa/usr/lib/node_modules/root
npm ERR! command failed
npm ERR! command sh -c lerna bootstrap && lerna link
npm ERR! sh: line 1: lerna: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2022-03-12T17_59_49_064Z-debug-0.log
==> ERROR: A failure occurred in package().
```

This is my PKGBUILD so far:
```bash
# Maintainer: NicoHood <archlinux {cat} nicohood {dog} de>
# PGP ID: 97312D5EB9D7AE7D0BD4307351DAE9B7C1AE9161

pkgname='bubblewrap-pwa'
_pkgname='bubblewrap'
pkgdesc="A command line tool to create a native android app from a PWA."
pkgver=1.15.0
pkgrel=1
arch=('any')
url="https://github.com/GoogleChromeLabs/"
license=('APACHE2')
depends=('jre8-openjdk-headless' 'nodejs>=12')
makedepends=('npm')
noextract=("${_pkgname}-${pkgver}.tgz")
source=("${pkgname}-${pkgver}.tar.gz::https://github.com/GoogleChromeLabs/${_pkgname}/archive/v${pkgver}.tar.gz")
sha512sums=('4808efd201276152f6e408de057c6de40cd5d2431876eae6bfb8eb0ab1ece8020bddbeebd2dd218052b9dd532a3fb434db596e89c16d37e74a642a9ee3e5084d')
validpgpkeys=('') # TODO

package() {
    npm install -g --user root --prefix "${pkgdir}"/usr "${srcdir}/${pkgname}-${pkgver}.tar.gz"

    # npm gives ownership of ALL FILES to build user
    # https://bugs.archlinux.org/task/63396
    chown -R root:root "${pkgdir}"
}
```

Any ideas what I am missing?

**Comment by andreban** [comment]
Great stuff, @NicoHood!

Could you add the content from the log file mentioned at the line below:
```
npm ERR!     /build/.npm/_logs/2022-03-12T17_59_49_064Z-debug-0.log
```

**Comment by NicoHood** [comment]
```
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/bin/npm',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   '--user',
0 verbose cli   'root',
0 verbose cli   '--prefix',
0 verbose cli   '/build/bubblewrap-pwa/pkg/bubblewrap-pwa/usr',
0 verbose cli   '/build/bubblewrap-pwa/src/bubblewrap-pwa-1.15.0.tar.gz'
0 verbose cli ]
1 info using npm@8.5.5
2 info using node@v17.8.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/build/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/build/bubblewrap-pwa/pkg/bubblewrap-pwa/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 14ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 24ms
18 timing npm:load:configload Completed in 24ms
19 timing npm:load:setTitle Completed in 0ms
20 timing config:load:flatten Completed in 3ms
21 timing npm:load:display Completed in 4ms
22 verbose logfile /build/.npm/_logs/2022-03-24T19_34_14_577Z-debug-0.log
23 timing npm:load:logFile Completed in 6ms
24 timing npm:load:timers Completed in 0ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load Completed in 35ms
27 timing arborist:ctor Completed in 1ms
28 timing idealTree:init Completed in 5ms
29 timing idealTree:userRequests Completed in 127ms
30 silly idealTree buildDeps
31 silly fetch manifest root@file:../../../../src/bubblewrap-pwa-1.15.0.tar.gz
32 silly placeDep ROOT root@0.4.3 OK for:  want: file:../../../../src/bubblewrap-pwa-1.15.0.tar.gz
33 timing idealTree:#root Completed in 100ms
34 timing idealTree:node_modules/root Completed in 0ms
35 timing idealTree:buildDeps Completed in 101ms
36 timing idealTree:fixDepFlags Completed in 1ms
37 timing idealTree Completed in 236ms
38 timing reify:loadTrees Completed in 239ms
39 timing reify:diffTrees Completed in 1ms
40 silly reify moves {}
41 timing reify:retireShallow Completed in 0ms
42 timing reify:createSparse Completed in 2ms
43 timing reify:loadBundles Completed in 0ms
44 silly audit bulk request { root: [ '0.4.3' ] }
45 timing reifyNode:node_modules/root Completed in 77ms
46 timing reify:unpack Completed in 77ms
47 timing reify:unretire Completed in 0ms
48 timing build:queue Completed in 0ms
49 info run root@0.4.3 postinstall node_modules/root lerna bootstrap && lerna link
50 info run root@0.4.3 postinstall { code: 127, signal: null }
51 timing reify:rollback:createSparse Completed in 34ms
52 timing reify:rollback:retireShallow Completed in 0ms
53 timing command:install Completed in 405ms
54 verbose stack Error: command failed
54 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
54 verbose stack     at ChildProcess.emit (node:events:527:28)
54 verbose stack     at maybeClose (node:internal/child_process:1090:16)
54 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
55 verbose pkgid root@0.4.3
56 verbose cwd /build/bubblewrap-pwa/src
57 verbose Linux 5.16.15-arch1-1
58 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--user" "root" "--prefix" "/build/bubblewrap-pwa/pkg/bubblewrap-pwa/usr" "/build/bubblewrap-pwa/src/bubblewrap-pwa-1.15.0.tar.gz"
59 verbose node v17.8.0
60 verbose npm  v8.5.5
61 error code 127
62 error path /build/bubblewrap-pwa/pkg/bubblewrap-pwa/usr/lib/node_modules/root
63 error command failed
64 error command sh -c lerna bootstrap && lerna link
65 error sh: line 1: lerna: command not found
66 verbose exit 127
67 timing npm Completed in 641ms
68 verbose unfinished npm timer reify 1648150454811
69 verbose unfinished npm timer reify:audit 1648150455084
70 verbose unfinished npm timer auditReport:getReport 1648150455084
71 verbose unfinished npm timer reify:build 1648150455164
72 verbose unfinished npm timer build 1648150455165
73 verbose unfinished npm timer build:deps 1648150455165
74 verbose unfinished npm timer build:run:postinstall 1648150455166
75 verbose unfinished npm timer build:run:postinstall:node_modules/root 1648150455166
76 verbose code 127
77 error A complete log of this run can be found in:
77 error     /build/.npm/_logs/2022-03-24T19_34_14_577Z-debug-0.log
```

**Comment by NicoHood** [comment]
One more info: I am building in a clean chroot. Some required dependencies might not be installed. It seems that this `lerna` is missing, however on my system it is also not installed, but the npm command finishes fine (as user install). So maybe lerna ist just an optional/fallback dependency for something else? Or maybe the error is just missleading. I dont know.

**Comment by andreban** [comment]
I'm wondering if the root cause is related to:

```
54 verbose stack Error: command failed
54 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
54 verbose stack     at ChildProcess.emit (node:events:527:28)
54 verbose stack     at maybeClose (node:internal/child_process:1090:16)
54 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

This StackOverflow question points out that installing with `--silent` might solve it: https://stackoverflow.com/questions/65602290/i-cant-execute-npm-scripts-in-node-why-is-this-happening-and-how-can-i-solve-it

Might be worth trying ` npm install -g --user root --prefix "${pkgdir}"/usr "${srcdir}/${pkgname}-${pkgver}.tar.gz" --silent` on PKGBUILD .

**Comment by NicoHood** [comment]
Does not help.

**Comment by andreban** [comment]
I'm not really an expert on Arch linux, so it may be a good idea o ask in their forums. We don't have plans to officially support other package managers other than NPM at this time though, so closing the issue.
