### ISSUE TITLE
Unexpected token error [PWABuilder]

### ISSUE THREAD

**Issue by amrutha95** [GoogleChromeLabs/bubblewrap#703]
**Describe the bug**

The [issue](https://github.com/pwa-builder/PWABuilder/issues/2777) was raised on the [PWABuilder](https://pwabuilder.com/) repo. We use bubblewrap to package TWAs. 
Version 1.17.0

This is the error: 
Error: Error generating Android package.
Status code: 500
Error: Internal Server Error
Details: Error generating app package:
Failed to download Web Manifest https://roocket.ir/manifest.json.Responded with status 503
stack: Error: Failed to download Web Manifest https://roocket.ir/manifest.json.Responded with status 503
at TwaGenerator.writeWebManifest (/app/node_modules/@bubblewrap/core/dist/lib/TwaGenerator.js:221:19)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at TwaGenerator.createTwaProject (/app/node_modules/@bubblewrap/core/dist/lib/TwaGenerator.js:350:13)
at BubbleWrapper.generateTwaProject (/app/build/bubbleWrapper.ts:112:9)
at BubbleWrapper.generateAppPackage (/app/build/bubbleWrapper.ts:53:9)
at createAppPackageWith403Fallback (/app/routes/project.ts:249:12)
at createAppPackage (/app/routes/project.ts:225:12)
at /app/routes/project.ts:36:24

<img width="343" alt="image" src="https://user-images.githubusercontent.com/22471775/172245579-924c18ad-4e4d-4234-a3a1-c28fdeb32647.png">

**To Reproduce**
bubblewrap init --manifest=https://roocket.ir/manifest.json

**Expected behavior**

**Comment by andreban** [comment]
@amrutha95 can you provide steps taken to check the issue before filing so we avoid repeating debugging?

In general, I'd recommend running `curl -v <manifest url>` before bringing the issue over from PWA Builder: 

Running `curl -v https://roocket.ir/manifest.json` shows the URL returns an HTML instead of a JSON, when not loaded from the browser :

<details><summary>Expand for the results</summary>
<p>

```
*   Trying 104.21.233.137:443...
* Connected to roocket.ir (104.21.233.137) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.roocket.ir
*  start date: Apr 10 11:01:09 2022 GMT
*  expire date: Jul  9 11:01:08 2022 GMT
*  subjectAltName: host "roocket.ir" matched cert's "roocket.ir"
*  issuer: C=US; O=Let's Encrypt; CN=E1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f93ae011400)
> GET /manifest.json HTTP/2
> Host: roocket.ir
> user-agent: curl/7.79.1
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 403 
< date: Tue, 07 Jun 2022 09:54:01 GMT
< content-type: text/html; charset=UTF-8
< cf-chl-bypass: 1
< permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
< cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< expires: Thu, 01 Jan 1970 00:00:01 GMT
< x-frame-options: SAMEORIGIN
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=D2yQGiu8DTRUt%2B%2Barg4I1A1HDk16gM%2FfpQldpy8QB%2BACTfF%2BqLN2a9P6v32Pc2FxxHQDFQwXI3FaRpwLExtx6QnVjN1eL7qzj86%2Bvau7IJ%2Ft9PfPHU38RUGQrDpC"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< strict-transport-security: max-age=15552000; includeSubDomains; preload
< x-content-type-options: nosniff
< server: cloudflare
< cf-ray: 717881051992f43b-LHR
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>

<title>Please Wait... | Cloudflare</title>
  
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->


    <script>
    //<![CDATA[
    (function(){
      window._cf_chl_opt={
        cvId: "2",
        cType: "managed",
        cNounce: "95950",
        cRay: "717881051992f43b",
        cHash: "de66bb499d0da21",
        cUPMDTk: "\/manifest.json?__cf_chl_tk=4DwWhvvRFIpEsIHyPoO6eFjmN5WBXwAa8DKtbfgd9EA-1654595641-0-gaNycGzNByU",
        cFPWv: "g",
        cTTimeMs: "1000",
        cLt: "n",
        cRq: {
          ru: "aHR0cHM6Ly9yb29ja2V0LmlyL21hbmlmZXN0Lmpzb24=",
          ra: "Y3VybC83Ljc5LjE=",
          rm: "R0VU",
          d: "TQA9cPkeF78VPYXgtlAGqQ+goxutQaFv4/jZjrmAd0abpW6GcvZEHPfdRHagXDDH5IWh1DWA2Zq5ToOfW+2QcGSRreafFIoY6idbK+o/xMdyi13ix8SEWNUgzQTpGqNjXdtiupSCExlSCta6u//+7rFenEnjCrpaSmGQRllv4Q85YCNyIFswxIT55PU0sSHD+l7+n5nyisyrJX3ktoOCH/ux8QynL5AZ5yQ1a7RVnKuuHuZgooP7f8e1OBl+HrVL5dz4i+GWSZY4z2NLsB9E9/mCJh6XbIPt+8l8EOytqWH78TI/m/Z5POAWVkGGYmixclnJ4a/d+IoWcv1E5yyP+G57lAg6oxHfIJDSzHaxj7UCiThhrqyLAQKpLvEGsU3AaW9UYtUrkZaTW0HPc1fyfxIMjFkqlRlD/WCiZBr/WWuPF8m1O6FyURxlGFbzGlaKHjPKBtdFstLi74hNuw23sGj5oYuuEjAmaYz7sD3rxKpFQCMlapxWgFOELZ8CVP/fLM9kLC49gHASP/7/ht7tnyzFSWUioCriF4aYJ8Y18hsnbGmFFGWTrfl50XWHtx7Lrqe3RAxBfmA0+G3E3c6Ebz2pQ6F2O2N0Ax/7pLEccIUEmwEeXLOfxCWSAg+Bxi7KMWo038hv9i2DeoeLpw3+Wc1bl5nuKd3yYHjIkAWr5GJotZ9Z0c5Yb7UoczPjDnTi",
          t: "MTY1NDU5NTY0MS4xNDEwMDA=",
          m: "StIjs5vKWUCnHydjQnby+o67/ryIX3zzCAiTH6aQWdQ=",
          i1: "3c2S/clVvIhKZ+gBOpinVw==",
          i2: "ZFchEIIkR1WZRRXPlXWHwg==",
          zh: "3bSI4ZvY5h0HQvPled/VQlPziyBUkP3otjFIAYDaNKM=",
          uh: "falndCMbwPZaI1tCsX87kuFM/7Evubc5zrKWaDOjabE=",
          hh: "fnI/VHcLWp0YdRMKm+B/rBNESozHrLeBYjqcpl7nk84=",
        }
      };
    }());
    //]]>
    </script>

<style>
  #cf-wrapper #spinner {width:69px; margin:  auto;}
  #cf-wrapper #cf-please-wait{text-align:center}
  .attribution {margin-top: 32px;}
  .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
  #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
  #cf-hcaptcha-container { text-align:center;}
  #cf-hcaptcha-container iframe { display: inline-block;}
  @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-wrapper #cf-bubbles { width:69px; }
  @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
  #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
  #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
</style>
</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
      
        <h1 data-translate="managed_challenge_headline">Please wait...</h1>
        <h2 class="cf-subheadline"><span data-translate="managed_checking_msg">We are checking your browser...</span> roocket.ir</h2>
      
      </div>
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form managed-form" id="challenge-form" action="/manifest.json?__cf_chl_f_tk=4DwWhvvRFIpEsIHyPoO6eFjmN5WBXwAa8DKtbfgd9EA-1654595641-0-gaNycGzNByU" method="POST" enctype="application/x-www-form-urlencoded">
    <div id='cf-please-wait'>
      <div id='spinner'>
        <div id="cf-bubbles">
            <div class="bubbles"></div>
            <div class="bubbles"></div>
            <div class="bubbles"></div>
        </div>
      </div>
      <p data-translate="please_wait" id="cf-spinner-please-wait">Please stand by, while we are checking your browser...</p>
      <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting...</p>
      </div>
  <input type="hidden" name="md" value="6iQYB_5tZ1DXdlB55XA0.nf2T1XGAUBnsGMUznWuyE0-1654595641-0-AfwqaWG1pnMFESDchyUmV-Yc4VpmgW997_Xg9wUCYdsddOyF-9iv3Kr7B4_Qx9O9N89yUszN9M2xbI-eEZK6zaioGK1UcTtdGn0iP_7xNRjT_UrlYer_OEEk4UebMb8skzYsL24YS52MsoBhKAIuXdZRKqO8g-yuUlifye9QvljqYNUfXU5X3CpKPk4ZV6EFPtTUJa4sbZkyvsGGUXMEudKBiBMC2Xtn2mWTyR7WIE11Azulezo4iDcWRyJvCcyWOvF0EFalDOv-I61UrVSKBItL7UMje81sgF9tNZY0hby9SW5DRt1e2vrGHu-wF7N5mgWt0hMn09gZiQg-DLzcKg4C8cyu9KwK3eiC1sr9OJAn_v8nP6M0sLdUgtbsoqkAUOBiLVAzHL2Yw0pVl9qN0rDGTlABF3FkhsHFOugzIrcZoxCUD9pmCT3QKSYJJ0Lh471i6MeTuyMad2YnzlwqMlpEzzXPAisE5aUPkMpMKiL85SVt2tAiSFVsExosZib-XlwDcAKaBtWP9LslVlJ-Lix-fdwzfJStcAhVmXExokWecBNRt384YUAgebdH5P6ZjbxciZMYg_awsz-IKyFlc6jKDHQeIyG70yALXhgugoUGZQfSSgs_igQayGaC5ar25AIG4F47yx_qHZuXC_jCJoYKBfxQ-IS2W66Rjx6dNgqwPVYS7JzIoEV6sd4n3nNRvH4TtSqzbb5T5ds-M2tWzQBwCqwSuUIIRs2FQkymDZAHOvgkSrAmHTQTBVcr4UWknDThgHcEGTXOGl2F1eoS2vgZl_qOwD5hvS5kzOBfNYwkG5qanPkQfFgwqYzLbiFroR9Fezs_tgfZvpiqtTe1fBR_8pXjnIF9SYVRqSjvsS4vIjowVAo-bVAgb1qO0NKcD70f3Z393xKUPlQt9TgluFCVOrBXzBtjBL1Eky0nYn2_" />
  <input type="hidden" name="r" value="._IIjj7cmC9sTp1E4kTcVbthKO74wlZiJsmaNRv.mEs-1654595641-0-AXvd+moGh7GNL5fIP4+KGzU1MCjWTmjhfTqwy/zLVu5ZEiMmtTrjpTFaP/PSqVQtmZEPBNvSYKIA2HUWQtQ+9SnzsN1rNSBBjAm3y7Yhan/cl9lbXzqYzATeB6gLB7KnmOMOIR9IB6/gYkTtJghlHLwtafnQPofGzIwCy3pVT0IffkDF512kqmbfKfOMNi/sgW7OjPTEoDtluGXfS8d+1EKMwjKPtJThy9BInOwUhv7do49VzvXf7ZcGBLM0mZXM6E6gA7/cXWGkKGbl2MN+OpYNUVU91gxh5Oy8pPZkGenwgNq13L+JbR0ztPhVDuHAvVmAJS/z8CWUBiLwahduPtVgBnz5dpUQSTUMzjmz0OxQd5aqyOTUdZbyJIAMvvVKjECAjH+H/JmG0SDDD9KSHKySCVqBeSrFsFkTjJmJkMEyECHyR0cNZ13WSaEmcyOAsxR4NPSePO0CD3SX3OOm/+DINg0AsGM3zZmN9VZNITMydWekwmYbM0FzkSo6hyLvlumr1rrooF+VEhUWbe+KIptD3okb68sbJqvQeswEKWsCJ0gKlwc61hq1qVbBLs4FsXNuvnobzfXwiotGRb47PWqFZJbIpGHh/GvDgaqsKFzJ7dcGG/X6n+/ifTZ6+m7PJHGBueY/yd146rTRLun6yTdYCld2vRaa/AMve2DzY7U4kKEw2Dkdl4T6Ih7UAJ3o/dYCBE8a4JD2s7UlEACAizLncWSdJ6J8PIEb4v6Nwe4yqnWNXBEl43/ljq4klcVWYTpQKaahw5Zi6w4BQoP00JBxGoePKqUFJoaAgPckC5pfaH38DGkeWI3BShiVGjxNVcSQMCGjBrwLOPVe77iS1cvEzsdsQ6bSvtBC3KUyfUQcRSXnxg7zu/82YH5LU4bQogFLyWNKNw8DIJTMgz2mcdomnP/o9T8n5dtFw1k2JmXmRTUak2IezNxofMTuXD+LE6hfXXCpFpfRawMwphdwRflwEtLYh+D/nwReS8XnhulLnjcto1IVwKGNc/MdByXrj+Vt2wEE54vN31/29sLm7nmAX6Z5wSdc9wsOZWv2xZqe2Uz3g40SaiFokHjRwXExIUhUdI5nOq6DYeJUGl7AMdFT0+3SiPVFlGDckrakNZau3WIB3Af2jAcL5a+Y2YQWGA2ATjfoiUQtPoz8C5GKC07UJAfu3UKMciTdQq+Ze+ACcQOs14Vu573IqhhwCVFU1j/ygrF4Hmhj1QDjlO6Vcwln8zHa25LDgvhcUCLSAqhQ1ZrVxzpRj2G11wG+r6P75vuSI7GXHkIieI5xGOYb7O20H/SmU/FZbiDOBzhJKJZTbqUaUuic+wOt9cjnPdC6ZIsrIdHLVqk+LuskmWJMVS0shsL7M4Iy29NDq2OZy89I/SY8m7RdpQ3BKbax/SsRkEsr5ofZ+WJaKJdSwr3RB7rcm3nH8tuMV7XjMQl/Bgcb25LRk5VPR0GLHcZPH/7bNBE2WhW157OGpKMncH7w1r3P4H3JXL4LGGxgm2stEyTxuiwMvCiKtzxIgn75PoFGV1JAS70TX/nBDEScVO1Y3NlfYwZABBU7RrEzp2c0i/gSeKKxoVTSTIUVVMElu5vJ+xzsMG2vCbxUWXUhN1An6ArznMC1oyOsG6KcCXxjRbBLVfpMDVqKsI0rpPdiIeQK1XU0qXEWDpK4A6EAgB9OfbZiJbm+cRPkBOBAK1F5jAggvFN2PHyHD6xNlbcOpwSOdQ3qA7P/7kgTzeCne983uksG46SvkXcmHgXC52CagsSR">
  <input type="hidden" name="vc" value="3738b705efd055021da1153dff9142db">
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
  <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
  <script>
  //<![CDATA[
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
      b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
      b(function(){
        var cookiesEnabled=(navigator.cookieEnabled)? true : false;
        if(!cookiesEnabled){
          var q = document.getElementById('no-cookie-warning');q.style.display = 'block';
        }
      });
  //]]>
  </script>
  <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=717881051992f43b')"></div>
</form>
  <script>
    //<![CDATA[
    (function(){
        var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
        var trkjs = isIE ? new Image() : document.createElement('img');
        trkjs.setAttribute("src", "/cdn-cgi/images/trace/managed/js/transparent.gif?ray=717881051992f43b");
        trkjs.id = "trk_managed_js";
        trkjs.setAttribute("alt", "");
        document.body.appendChild(trkjs);
        var cpo=document.createElement('script');
        cpo.type='text/javascript';
        cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=717881051992f43b";
        
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window._cf_chl_opt.cUPMDTk && window.history && window.history.replaceState) {
          var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
          history.replaceState(null, null, "\/manifest.json?__cf_chl_rt_tk=4DwWhvvRFIpEsIHyPoO6eFjmN5WBXwAa8DKtbfgd9EA-1654595641-0-gaNycGzNByU" + window._cf_chl_opt.cOgUHash);
          cpo.onload = function() {
            history.replaceState(null, null, ogU);
          };
        }
        
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
    //]]>
    </script>


              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
            
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
            

            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
            
              
            
          </div>
        </div>
      </div>
      <a href="https://nhs-foi.com/aberrantgrump.php?ld=7162"><span style="display: none;">table</span></a>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">717881051992f43b</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 77.96.185.83</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
  </div>

  <script>
  window._cf_translation = {};
  
  
</script>


</body>
</html>
* Connection #0 to host roocket.ir left intact
```

</p></details>

https://github.com/pwa-builder/PWABuilder/issues/2777, however, is about a different URL:  `https://tekye.net/site.webmanifest/`. Running `curl -v  https://tekye.net/site.webmanifest` shows the server returns a 500 error when the URL is loaded outside the browser:

<details><summary>Expand for the results</summary>

```
❯ curl -v https://tekye.net/site.webmanifest
*   Trying 185.120.222.125:443...
* Connected to tekye.net (185.120.222.125) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=tekye.net
*  start date: May  5 18:24:33 2022 GMT
*  expire date: Aug  3 18:24:32 2022 GMT
*  subjectAltName: host "tekye.net" matched cert's "tekye.net"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fb1e600b600)
> GET /site.webmanifest HTTP/2
> Host: tekye.net
> user-agent: curl/7.79.1
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 500 
< server: openresty
< date: Tue, 07 Jun 2022 09:59:09 GMT
< content-length: 0
< cache-status: 0
< 
* Connection #0 to host tekye.net left intact
```

</details>
 
Error messages can be improved, but the underlying issue in both cases is that the remote server is not returning a valid JSON.
