### ISSUE TITLE
Android 13 (SDK 33) Crash

### ISSUE THREAD

**Issue by qertis** [GoogleChromeLabs/bubblewrap#723]
Pre-launch report details from Google Play Console

## Device specifications:

Model name: Redfin 64-bit only
Manufacturer: google
Android version: Android 13 (SDK 33)
Locale: en_US
Screen size: 1080 x 2340
Screen density (DPI): 440
ABI: arm64-v8a

## Stacktrace:

```
FATAL EXCEPTION: main
PID: 26575
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.internal.app.procstats.UidState.updateCombinedState(int, long)' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.IActivityManager$Stub$Proxy.attachApplication(IActivityManager.java:5148)
	at android.app.ActivityThread.attach(ActivityThread.java:7586)
	at android.app.ActivityThread.main(ActivityThread.java:7885)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by mhanzla80** [comment]
I am having the same error does any body have any solution ?

**Comment by claudiotouchard** [comment]
Me too...any solution ?

**Comment by Sir-RenderZ** [comment]
I am having this exact same issue as well.

**Comment by qzzf1w** [comment]
Mee too

**Comment by luimtersta** [comment]
I have the problem too, I'm doing nothing special in-app, it's new SDK, it's not rare this happens, just should ignore and if you have more problems in advance there will be more documentation
