### ISSUE TITLE
alias key not working

### ISSUE THREAD

**Issue by 2803media** [GoogleChromeLabs/bubblewrap#800]
Hi all

I have an app already published on the store and I need to update it. I have the keystore password but the alias 'android' password doesn't work... As I remember the 2 passwords are similar but it doesn't work....

```
cli ERROR Command failed: /Users/test/Library/Android/sdk/build-tools/33.0.2/apksigner sign --ks /Users/test/Documents/SitesWeb/ticks/TWA/android.keystore --ks-key-alias android --ks-pass pass:XXXXXXX --key-pass pass:XXXXXXX --out ./app-release-signed.apk ./app-release-unsigned-aligned.apk
Failed to load signer "signer #1"
java.io.IOException: Failed to obtain key with alias "android" from /Users/test/Documents/SitesWeb/ticks/TWA/android.keystore. Wrong password?
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:329)
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
        at com.android.apksigner.ApkSignerTool.getSignerConfig(ApkSignerTool.java:419)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:336)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:92)
Caused by: java.security.UnrecoverableKeyException: Cannot recover key
        at sun.security.provider.KeyProtector.recover(KeyProtector.java:315)
        at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:143)
        at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:57)
        at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:71)
        at java.security.KeyStore.getKey(KeyStore.java:1023)
        at com.android.apksigner.SignerParams.getKeyStoreKey(SignerParams.java:384)
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:297)
        ... 4 more
```

Do you know how I can find a way to get off this problem?

Thanks

**Comment by arunkjojo** [comment]
How was it fix?
Thanks for your update

**Comment by 2803media** [comment]
As I remember I uninstall everything and update to the last version of node and the package, I guess (if I remember the node version was too old)
